"""Render the narrative insights document (output/insights.md)."""

import os


def _fmt_pct(x):
    return f"{x}%" if x is not None else "n/a"


def render_markdown(records, rollups, output_dir):
    t = rollups["totals"]
    sbt = rollups["sentiment_by_type"]
    lines = []
    A = lines.append

    A("# Transcript Intelligence — Findings & Recommendations\n")
    A("_Generated by `transcript_intelligence/pipeline.py` — zero external "
      "dependencies, fully reproducible._\n")
    A(f"**Dataset:** {t['n_calls']} call transcripts across "
      f"{t['n_call_types']} call types "
      f"({', '.join(f'{k}: {v}' for k, v in sorted(t['by_type'].items()))}).\n")

    # ---- Task 1: categorisation ----
    A("\n## 1. Topic / Theme Categorisation\n")
    A("**Approach — hybrid, rule-based over upstream signals.** Every transcript "
      "already ships with a model-generated `topics` array and typed `keyMoments`. "
      "Rather than spend a second LLM pass (slower, non-deterministic, harder to "
      "defend to a leadership panel), I map those signals into a fixed, human-named "
      "taxonomy with a transparent keyword rule set. It is auditable, instant, and "
      "reproducible — and it degrades gracefully (`Other / Uncategorised`) when "
      "nothing matches. A clustering/LLM pass is the natural next step once the "
      "taxonomy needs to discover *new* themes rather than sort into known ones.\n")
    A("\n**Call-type inference.** The raw data has no call-type field, so I derive "
      "it: a `Support Case #…` title ⇒ **support**; any non-Aegis email domain in "
      "the room ⇒ **external** (customer present); everyone on `aegiscloud.com` ⇒ "
      "**internal**.\n")
    A("\n| Theme | Calls | Avg sentiment (1–5) | % with churn signal |")
    A("|---|---:|---:|---:|")
    for theme, n in rollups["theme_counts"].items():
        ts = rollups["theme_sentiment"][theme]
        A(f"| {theme} | {n} | {ts['avg_score']} | {ts['pct_churn']}% |")

    A("\n**Example transcripts per theme:**\n")
    seen = set()
    examples = {}
    for r in records:
        examples.setdefault(r["primary_theme"], [])
        if len(examples[r["primary_theme"]]) < 3:
            examples[r["primary_theme"]].append(r["title"])
    for theme in rollups["theme_counts"]:
        A(f"- **{theme}** — " + "; ".join(f"_{x}_" for x in examples.get(theme, [])))

    # ---- Task 2: sentiment ----
    A("\n## 2. Sentiment Analysis Across Call Types\n")
    A("| Call type | Calls | Avg score (1–5) | Avg negativity ratio | % calls w/ churn signal |")
    A("|---|---:|---:|---:|---:|")
    for ctype, s in sorted(sbt.items()):
        A(f"| {ctype} | {s['count']} | {s['avg_score']} | "
          f"{s['avg_negativity_ratio']} | {_fmt_pct(s['pct_with_churn_signal'])} |")

    # Derive the storyline dynamically so the prose matches the data.
    ranked = sorted(sbt.items(), key=lambda kv: kv[1]["avg_score"] or 0)
    worst, best = ranked[0], ranked[-1]
    A("\n**What the trend means.**\n")
    A(f"- **{worst[0].title()} calls are the emotional low point** "
      f"(avg {worst[1]['avg_score']}/5, churn signal in "
      f"{worst[1]['pct_with_churn_signal']}% of calls). These are the conversations "
      f"where customers are actively frustrated — they are the leading indicator of "
      f"revenue at risk, not a lagging support metric.")
    A(f"- **{best[0].title()} calls sit highest** (avg {best[1]['avg_score']}/5). ")
    A("- The gap between the most-negative and most-positive call type is the single "
      "most useful operational signal here: it tells leadership *where the customer "
      "pain is concentrated* and therefore where a CS / reliability intervention buys "
      "the most retention.\n")
    A("> **Why care:** sentiment on its own is a vanity chart. Tied to call type and "
      "to churn signals, it becomes a prioritisation tool — it ranks which accounts "
      "and which workflows to fix first.\n")

    # ---- Task 3: bonus insights ----
    A("\n## 3. What Else Can You See? (Bonus Insights)\n")

    o = rollups["outage"]
    A(f"\n### 3.1 Outage Blast Radius — incident → revenue map (CS / Eng leaders)\n")
    A(f"The 'Detect' outage is not one incident — while only **{o['n_primary_calls']} "
      f"calls** are *primarily* about it, its ripples surface across "
      f"**{o['n_calls']} calls** and touch **{o['n_customers_touched']} distinct "
      f"customers**: {', '.join(o['customers_touched'])}. Internally it shows up as war "
      f"rooms and post-mortems; externally as renewal-risk and escalation calls. "
      f"Stitching the internal incident timeline to the external customer calls it "
      f"generated gives leadership a single 'one outage cost us *these* accounts' view "
      f"— the kind of artefact that justifies reliability investment.\n")

    A("\n### 3.2 Churn-Risk Early-Warning Board (CS / Sales leaders)\n")
    A("Combining low sentiment score + presence of a `churn_signal` key moment "
      "across an account's calls produces a ranked watch-list **before** the renewal "
      "conversation goes bad. Top accounts by churn signals:\n")
    A("\n| Account | Calls | Calls w/ churn signal | Avg sentiment |")
    A("|---|---:|---:|---:|")
    for acc in rollups["churn_ranked"][:8]:
        if acc["churn_calls"]:
            A(f"| {acc['customer']} | {acc['calls']} | {acc['churn_calls']} | "
              f"{acc['avg_score']} |")

    A("\n### 3.3 Aggregated Feature-Gap Demand (Product leaders)\n")
    A(f"`feature_gap` key moments appear across "
      f"{len(rollups['feature_gap_calls'])} calls. Rolling them up turns scattered "
      f"customer asks into a demand-weighted backlog — 'how many paying accounts "
      f"asked for X' — which is far more persuasive in roadmap planning than a single "
      f"loud customer. Sample gaps:\n")
    for fg in rollups["feature_gap_calls"][:6]:
        if fg["moments"]:
            A(f"- _{fg['title']}_ ({fg['customer'] or 'internal'}): {fg['moments'][0]}")

    A("\n### 3.4 Action-Item Accountability Tracker (every leader)\n")
    A("Every call carries explicit `actionItems` with named owners. Extracting and "
      "grouping them by owner/account creates a cross-call commitment ledger — who "
      "promised what, and whether the next call references it being done. This is a "
      "lightweight way to measure follow-through, which is invisible in any single "
      "transcript.\n")

    # ---- Method & caveats ----
    A("\n## 4. Method, Caveats & Next Steps\n")
    A("- **Reproducibility:** stdlib-only, deterministic — `python pipeline.py` "
      "regenerates `results.json`, `insights.md`, and `report.html` identically.\n")
    A("- **Trust the upstream labels, but verify:** sentiment and key-moment types "
      "are model-generated. I treat them as features, not ground truth; the next "
      "step is a spot-check sample to estimate label precision before acting on the "
      "churn board.\n")
    A("- **Scaling:** the rule-based taxonomy is a starting point. At 10k+ "
      "transcripts I would add embedding clustering to surface *emergent* themes the "
      "fixed taxonomy can't name, then fold the good clusters back into the rules.\n")

    path = os.path.join(output_dir, "insights.md")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))
    return path
